# node-etsy-client continuous integration
name: main

# Controls when the action will run.
on:
  # Triggers the workflow on pull request or push (only for the npmjs branch)
  push:
    branches: [ npmjs ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ETSY_SHOP: fakefakefakefake

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          # version from package.json
          run_install: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          echo ::group::Install dependencies
          echo "install"
          pnpm install
          echo "setup : c8 required for coverage"
          pnpm run setup
          echo ::endgroup::

      - name: CHECK - Check for outdated dependencies (non-blocking warning)
        run: |
          echo "🔍 Checking for outdated dependencies..."
          if pnpm outdated --depth=3; then
            echo "::notice title=Deps OK::✅ Dependencies are up to date 🎉"
          else
            echo "::warning title=ℹ️ Outdated Dependencies::Some dependencies are outdated. Please consider updating them."
          fi

      - name: CHECK - pnpm audit inline (prod deps only)
        if: ${{ github.actor == 'dependabot[bot]' || !(github.event_name == 'pull_request') }}
        run: |
          pnpm audit --prod --audit-level=high > audit.txt && echo "::info::✅ No vulnerabilities found" || (echo "::warning::❌ Vulnerabilities found";cat audit.txt)

      - name: CHECK - pnpm audit and comment on PR
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request }}
        uses: JamesRobertWiseman/pnpm-audit@v3.2.0
        with:
          prod: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: moderate   # 'low'|'moderate'|'high'|'critical'
          fails: false # true to fail the build if vulnerabilities are found
          single_comment: true # true to only post one comment
          inline: true # true to emit audit findings directly in the workflow logs using GitHub annotation syntax

      - name: Run ci-tests with code coverage
        run: |
          npm run ci-test

      - name: COVERAGE - Report coverage on pull request
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request }}
        continue-on-error: true
        # uses: romeovs/lcov-reporter-action@v0.2.16 # https://github.com/romeovs/lcov-reporter-action/issues/10
        uses: andybelltree/lcov-reporter-action@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: coverage/lcov.info
          filter-changed-files: true

      - name: Publish NpmJS package with NPM_DEPLOY_TOKEN
        if: github.ref == 'refs/heads/npmjs'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_DEPLOY_TOKEN }}" > .npmrc
          pnpm whoami
          pnpm publish

      - name: "Deploy Github Pages (code-coverage)"
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: coverage/